/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Admin/dashboard': RouteRecordInfo<'/Admin/dashboard', '/Admin/dashboard', Record<never, never>, Record<never, never>>,
    '/Admin/status': RouteRecordInfo<'/Admin/status', '/Admin/status', Record<never, never>, Record<never, never>>,
    '/Admin/status2': RouteRecordInfo<'/Admin/status2', '/Admin/status2', Record<never, never>, Record<never, never>>,
    '/CPDO/CPDOdashboard': RouteRecordInfo<'/CPDO/CPDOdashboard', '/CPDO/CPDOdashboard', Record<never, never>, Record<never, never>>,
    '/CPDO/status': RouteRecordInfo<'/CPDO/status', '/CPDO/status', Record<never, never>, Record<never, never>>,
    '/Engr/dashboard': RouteRecordInfo<'/Engr/dashboard', '/Engr/dashboard', Record<never, never>, Record<never, never>>,
    '/Engr/status': RouteRecordInfo<'/Engr/status', '/Engr/status', Record<never, never>, Record<never, never>>,
    '/page': RouteRecordInfo<'/page', '/page', Record<never, never>, Record<never, never>>,
  }
}
